[target.'cfg(target_os="macos")']
# Postgres symbols won't be available until runtime
rustflags = ["-Clink-arg=-Wl,-undefined,dynamic_lookup"]

#[target.'cfg(windows)']
#rustflags = ["-C", "link-args=-Wl,-undefined,dynamic_lookup"]
[target.'cfg(windows)']
rustflags = ["-C", "link-arg=-Wl,-undefined"]
#rustflags = "-C link-arg=-Wl,-undefined,dynamic_lookup"